"use client";
import {useEffect,useState} from "react";
import {Search,Play,Plus,Info} from "lucide-react";
type Movie={id:number;title?:string;name?:string;overview:string;poster_path:string|null;backdrop_path:string|null;vote_average:number;release_date?:string;first_air_date?:string};
const img=(p:string|null,size="w500")=>p?"https://image.tmdb.org/t/p/"+size+p:"https://placehold.co/500x750/171717/ffffff?text=Streamflix";
function Row({title,items,onOpen}:{title:string;items:Movie[];onOpen:(m:Movie)=>void}){return <section className="mb-9"><div className="mb-3 flex items-center justify-between px-5 md:px-10"><h2 className="text-xl font-bold md:text-2xl">{title}</h2><span className="text-sm text-zinc-400">Explore</span></div><div className="scrollbar-hide flex gap-3 overflow-x-auto px-5 md:px-10">{items.map(m=><button key={m.id} onClick={()=>onOpen(m)} className="card min-w-[145px] text-left md:min-w-[190px]"><img src={img(m.poster_path)} className="aspect-[2/3] w-full rounded-md object-cover" alt={m.title||m.name||""}/><div className="mt-2 truncate text-sm font-semibold">{m.title||m.name}</div><div className="text-xs text-zinc-400">★ {m.vote_average?.toFixed(1)}</div></button>)}</div></section>}
export default function Home(){
 const [data,setData]=useState<Record<string,Movie[]>>({}); const [hero,setHero]=useState<Movie|null>(null); const [q,setQ]=useState(""); const [results,setResults]=useState<Movie[]>([]); const [selected,setSelected]=useState<Movie|null>(null); const [list,setList]=useState<Movie[]>([]);
 const api=async(path:string)=>{const r=await fetch("/api/tmdb?path="+encodeURIComponent(path));if(!r.ok)throw new Error("TMDB unavailable");return r.json()};
 useEffect(()=>{Promise.all([api("/trending/all/week?language=en-US"),api("/movie/popular?language=en-US&page=1"),api("/tv/popular?language=en-US&page=1"),api("/movie/top_rated?language=en-US&page=1")]).then(([t,m,tv,top])=>{setHero(t.results[0]);setData({Trending:t.results,Popular:m.results,TV:tv.results,TopRated:top.results})}).catch(console.error)},[]);
 useEffect(()=>{if(!q.trim()){setResults([]);return}const x=setTimeout(()=>api("/search/multi?query="+encodeURIComponent(q)+"&include_adult=false&language=en-US&page=1").then(d=>setResults(d.results?.filter((m:Movie)=>m.media_type!=="person")||[])).catch(()=>{}),350);return()=>clearTimeout(x)},[q]);
 const add=(m:Movie)=>{if(!list.some(x=>x.id===m.id))setList([...list,m])};
 return <main className="min-h-screen bg-[#050505] pb-10">
 {hero&&<header className="relative h-[70vh] min-h-[520px] overflow-hidden"><img src={img(hero.backdrop_path,"original")} className="absolute inset-0 h-full w-full object-cover opacity-70" alt=""/><div className="hero-gradient absolute inset-0"/><nav className="relative z-10 flex items-center justify-between px-5 py-5 md:px-10"><div className="text-2xl font-black tracking-tight text-red-600">STREAMFLIX</div><div className="flex items-center gap-4"><div className="relative hidden sm:block"><Search className="absolute left-3 top-2.5 h-4 w-4 text-zinc-400"/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search movies & TV..." className="w-64 rounded-full border border-white/20 bg-black/60 py-2 pl-10 pr-4 text-sm outline-none focus:border-white/50"/></div><button className="rounded-full bg-white/10 px-4 py-2 text-sm">My List ({list.length})</button></div></nav><div className="relative z-10 flex h-[calc(100%-90px)] max-w-3xl flex-col justify-end px-5 pb-16 md:px-10"><p className="mb-3 text-sm font-bold uppercase tracking-[.25em] text-red-500">Featured this week</p><h1 className="text-4xl font-black md:text-6xl">{hero.title||hero.name}</h1><p className="mt-4 max-w-2xl text-sm leading-6 text-zinc-200 md:text-base">{hero.overview}</p><div className="mt-6 flex gap-3"><button onClick={()=>setSelected(hero)} className="flex items-center gap-2 rounded-md bg-white px-6 py-3 font-bold text-black"><Play className="h-5 w-5 fill-current"/> Play</button><button onClick={()=>add(hero)} className="flex items-center gap-2 rounded-md bg-zinc-700/80 px-6 py-3 font-bold"><Plus/> My List</button><button onClick={()=>setSelected(hero)} className="flex items-center gap-2 rounded-md bg-white/15 px-5 py-3 font-bold"><Info/> Details</button></div></div></header>}
 {q&&<section className="absolute left-5 right-5 z-30 mt-[-90px] rounded-xl border border-white/10 bg-zinc-950 p-4 shadow-2xl md:left-auto md:right-10 md:w-[520px]"><h3 className="mb-3 font-bold">Search results</h3>{results.slice(0,6).map(m=><button onClick={()=>setSelected(m)} key={m.id} className="flex w-full gap-3 border-b border-white/5 py-2 text-left last:border-0"><img src={img(m.poster_path,"w92")} className="h-16 w-11 rounded object-cover"/><div><div className="font-semibold">{m.title||m.name}</div><div className="text-xs text-zinc-400">{m.release_date||m.first_air_date||"TV"} · ★ {m.vote_average?.toFixed(1)}</div></div></button>)}</section>}
 <div className="pt-8">{data.Trending&&<Row title="Trending Now" items={data.Trending} onOpen={setSelected}/>} {data.Popular&&<Row title="Popular Movies" items={data.Popular} onOpen={setSelected}/>} {data.TV&&<Row title="Popular TV Shows" items={data.TV} onOpen={setSelected}/>} {data.TopRated&&<Row title="Top Rated" items={data.TopRated} onOpen={setSelected}/>}</div>
 <footer className="mt-12 border-t border-white/10 px-5 py-8 text-center text-xs text-zinc-500">Streamflix uses TMDB for movie and TV metadata. Streamflix does not host copyrighted video content.</footer>
 {selected&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/80 p-5" onClick={()=>setSelected(null)}><div onClick={e=>e.stopPropagation()} className="max-h-[90vh] w-full max-w-3xl overflow-auto rounded-xl bg-zinc-900 shadow-2xl"><img src={img(selected.backdrop_path,"w1280")} className="h-56 w-full object-cover" alt=""/><div className="p-6"><h2 className="text-3xl font-black">{selected.title||selected.name}</h2><p className="mt-2 text-sm text-zinc-400">★ {selected.vote_average?.toFixed(1)} · {selected.release_date||selected.first_air_date||"Release date unknown"}</p><p className="mt-5 leading-7 text-zinc-200">{selected.overview||"No description available."}</p><div className="mt-6 flex gap-3"><button className="rounded-md bg-white px-5 py-3 font-bold text-black"><Play className="mr-2 inline h-4 w-4 fill-current"/> Play authorized source</button><button onClick={()=>add(selected)} className="rounded-md bg-zinc-700 px-5 py-3"><Plus className="mr-2 inline h-4 w-4"/> My List</button></div></div></div></div>}
 </main>
}